version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
