version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"  # Nem közvetlenül érhető el a külvilág számára
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000"  # Nem közvetlenül érhető el a külvilág számára

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"  # Az Nginx lesz elérhető a külvilág számára
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro